name: Build

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ '12', '14' ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Prepare
      run: prepare/main.sh
    - name: Build
      run: npm run build
    - name: Build documentation
      run: npm run doc
    - name: Test
      run: npm test
