name: Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: npm install
    - name: Prepare
      run: python prepare/main.py
    - name: Test
      run: npm test
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
